#!/usr/bin/env python3
"""
Phase E4-fix-mixed: Fix 141 mixed English/Chinese translations systematically.

These are terms where the translation engine left some English words untranslated
(e.g., "chilled水" → should be "冷冻水", "circulating水plant" → "循环水厂").
The fix replaces leftover English words with their Chinese equivalents.

Usage: python3 scripts/phase-e4-fix-mixed.py
"""
import json, re
from pathlib import Path

BASE = Path(__file__).parent.parent
KB = BASE / "knowledge-base"

KNOWN_ACRONYMS = {
    "3d", "cad", "cam", "cae", "capp", "pdm", "plm", "erp", "mrp", "cims",
    "cnc", "nc", "dnc", "fms", "cmm", "plc", "pid", "hmi", "scada", "dcs",
    "led", "lcd", "abs", "esp", "iso", "gb", "ansi", "din", "jis",
    "pwm", "vfd", "ac", "dc", "rpm", "hp", "kw", "hz",
    "mig", "tig", "mag", "ndt", "fmea", "spc",
    "vdi", "api", "asme", "astm", "sae", "iec",
}

# Word replacements for common untranslated words found in mixed terms
WORD_FIXES = {
    # Found in the mixed terms
    "water": "水",
    "plant": "厂",
    "condition": "条件",
    "machine": "机器",
    "engineering": "工程",
    "system": "系统",
    "design": "设计",
    "analysis": "分析",
    "production": "生产",
    "manufacturing": "制造",
    "manufacturer": "制造商",
    "structure": "结构",
    "equipment": "设备",
    "chilled": "冷冻",
    "cooling": "冷却",
    "heating": "加热",
    "ventilation": "通风",
    "air": "空气",
    "flow": "流动",
    "bench": "试验台",
    "test": "试验",
    "testing": "试验",
    "coefficient": "系数",
    "chart": "图",
    "cycle": "循环",
    "duty": "工作",
    "model": "模型",
    "theory": "理论",
    "method": "方法",
    "function": "功能",
    "control": "控制",
    "process": "工艺",
    "multi": "多",
    "structure": "结构",
    "connecting": "连接",
    "connection": "连接",
    "mating": "配合",
    "fitting": "配合",
    "joint": "接头",
    "plumbing": "管道",
    "mechanical": "机械",
    "electrical": "电气",
    "electronic": "电子",
    "hydrostatic": "静压",
    "hydraulic": "液压",
    "pneumatic": "气动",
    "sacrificial": "牺牲",
    "part": "零件",
    "parts": "零件",
    "component": "部件",
    "assembly": "装配",
    "unit": "单元",
    "module": "模块",
    "element": "元件",
    "body": "体",
    "head": "头",
    "base": "底座",
    "plate": "板",
    "pipe": "管",
    "tube": "管",
    "filter": "过滤器",
    "valve": "阀",
    "pump": "泵",
    "tank": "箱",
    "chamber": "室",
    "converter": "转换器",
    "driver": "驱动器",
    "actuator": "执行器",
    "sensor": "传感器",
    "transducer": "传感器",
    "logic": "逻辑",
    "network": "网络",
    "interface": "接口",
    "protocol": "协议",
    "standard": "标准",
    "specification": "规范",
    "parameter": "参数",
    "variable": "变量",
    "quantity": "量",
    "ratio": "比",
    "factor": "因子",
    "index": "指标",
    "level": "水平",
    "degree": "度",
    "angle": "角度",
    "measure": "测量",
    "measurement": "测量",
    "monitoring": "监测",
    "protection": "保护",
    "maintenance": "维护",
    "inspection": "检验",
    "calibration": "校准",
    "configuration": "配置",
    "arrangement": "布置",
    "layout": "布局",
    "diagram": "图",
    "schematic": "示意图",
    "drawing": "图纸",
    "documentation": "文档",
    "information": "信息",
    "data": "数据",
    "database": "数据库",
    "software": "软件",
    "program": "程序",
    "algorithm": "算法",
    "simulation": "仿真",
    "optimization": "优化",
    "operation": "操作",
    "performance": "性能",
    "efficiency": "效率",
    "reliability": "可靠性",
    "durability": "耐久性",
    "service": "服务",
    "support": "支持",
    "energy": "能量",
    "power": "功率",
    "force": "力",
    "pressure": "压力",
    "temperature": "温度",
    "velocity": "速度",
    "speed": "速度",
    "acceleration": "加速度",
    "frequency": "频率",
    "amplitude": "振幅",
    "capacity": "容量",
    "volume": "体积",
    "weight": "重量",
    "mass": "质量",
    "density": "密度",
    "viscosity": "黏度",
    "hardness": "硬度",
    "strength": "强度",
    "roughness": "粗糙度",
    "finish": "精加工",
    "surface": "表面",
    "edge": "边缘",
    "hole": "孔",
    "slot": "槽",
    "groove": "沟槽",
    "thread": "螺纹",
    "key": "键",
    "spline": "花键",
    "gear": "齿轮",
    "bearing": "轴承",
    "shaft": "轴",
    "spring": "弹簧",
    "screw": "螺钉",
    "bolt": "螺栓",
    "nut": "螺母",
    "washer": "垫圈",
    "pin": "销",
    "rivet": "铆钉",
    "weld": "焊缝",
    "casting": "铸件",
    "forging": "锻件",
    "heisler": "海斯勒",
    "junker": "容克",
    "ortman": "奥特曼",
    "reynolds": "雷诺",
    "timken": "铁姆肯",
    "west": "韦斯特",
    "beale": "比尔",
    "euler": "欧拉",
    "bernoulli": "伯努利",
    "lagrange": "拉格朗日",
    "laplace": "拉普拉斯",
    "fourier": "傅里叶",
    "navier": "纳维耶",
    "stokes": "斯托克斯",
    "maxwell": "麦克斯韦",
    "newton": "牛顿",
    "kepler": "开普勒",
    "mach": "马赫",
    "rayleigh": "瑞利",
    "prandtl": "普朗特",
    "nusselt": "努塞尔",
    "peclet": "佩克莱",
    "grashof": "格拉肖夫",
    "strouhal": "斯特劳哈尔",
    "coulomb": "库仑",
    "ampere": "安培",
    "volt": "伏特",
    "ohm": "欧姆",
    "watt": "瓦特",
    "joule": "焦耳",
    "pascal": "帕斯卡",
    "kelvin": "开尔文",
    "celsius": "摄氏度",
    "centigrade": "摄氏度",
    "fahrenheit": "华氏度",
    "rankine": "兰氏度",
    "concurrent": "并行",
    "adaptive": "自适应",
    "adaptive": "自适应",
    "original": "原始",
    "statistical": "统计",
    "associating": "关联",
    "fluid": "流体",
    "intermittent": "间歇",
    "sieving": "筛分",
    "time": "时间",
    "history": "历史",
    "powered": "驱动",
    "vehicle": "车辆",
    "vehicle": "车辆",
    "challenge": "挑战",
    "award": "奖",
    "excellence": "优秀",
    "british": "英国",
    "international": "国际",
    "space": "空间",
    "station": "站",
    "dry": "干",
    "mortar": "砂浆",
    "production": "生产",
    "line": "线",
    "manufacture": "制造",
    "medium": "介质",
    "contact": "接触",
    "cuttings": "岩屑",
    "cleaner": "清洗机",
    "thermomechanical": "热机械",
    "formula": "公式",
    "formulae": "公式",
    "weirs": "堰",
    "run": "运行",
    "coil": "线圈",
    "ok": "可",
    "load": "负载",
    "chilled": "冷冻",
    "circulating": "循环",
    "duty": "工作",
    "heisler": "海斯勒",
    "junker": "容克",
    "ortman": "奥特曼",
    "poly": "多",
    "clip": "卡夹",
    "reynolds": "雷诺",
    "timken": "铁姆肯",
    "west": "韦斯特",
    "beale": "比尔",
    "aisc": "AISC",
    "sacrificial": "牺牲",
    "sieving": "筛分",
    "thermomechanical": "热机械",
    "cuttings": "岩屑",
    "cleaner": "清洗机",
    "concurrent": "并行",
    "adaptive": "自适应",
    "simple": "简单",
    "gun": "枪",
    "drill": "钻",
    "leak": "泄漏",
    "down": "向下",
    "original": "原始",
    "statistical": "统计",
    "associating": "关联",
    "intermittent": "间歇",
    "feedwater": "给水",
    "anti": "反",
    "sweatshop": "血汗工厂",
    "movement": "运动",
    "run": "运行",
    "coil": "线圈",
    "timeline": "时间线",
    "jet": "喷射",
    "shop": "车间",
    "job": "作业",
    "kunkel": "孔克尔",
    "garbage": "垃圾",
    "rube": "鲁布",
    "goldberg": "戈德堡",
    "dunkerley": "邓克利",
    "third": "第三",
    "medium": "介质",
    "dry": "干",
    "mortar": "砂浆",
    "combined": "组合",
    "bazin": "巴赞",
    "weirs": "堰",
    "converting": "转换",
    "culvert": "涵洞",
    "safety": "安全",
    "barriers": "屏障",
    "dams": "坝",
    "spillway": "溢洪道",
    "electrostatic": "静电",
    "precipitator": "沉淀器",
    "online": "在线",
    "calculators": "计算器",
    "equal": "等",
    "solid": "实心",
    "commercial": "商业",
    "lumber": "木材",
    "sizes": "尺寸",
    "minimum": "最小",
    "ultimate": "极限",
    "tensile": "拉伸",
    "proof": "验证",
    "channel": "槽钢",
    "indian": "印度",
    "flange": "法兰",
    "beams": "梁",
    "reinforcing": "钢筋",
    "rebar": "钢筋",
    "rectangular": "矩形",
    "concrete": "混凝土",
    "cantilevered": "悬臂",
    "spreadsheet": "电子表格",
    "ideal": "理想",
    "pinned": "铰接",
    "buckling": "屈曲",
    "fixed": "固定",
    "pinned": "铰支",
    "supported": "支承",
    "uniformly": "均匀",
    "distributed": "分布",
    "partially": "部分",
    "overhanging": "外伸",
    "continuous": "连续",
    "spans": "跨",
    "calculator": "计算器",
    "baseplate": "底板",
    "moment": "力矩",
    "nonuniform": "非均匀",
    "diameter": "直径",
    "change": "变化",
    "length": "长度",
    "axial": "轴向",
    "american": "美国",
    "narrow": "窄",
    "shapes": "形状",
    "angles": "角钢",
    "unequal": "不等",
    "legs": "肢",
    "inclined": "倾斜",
    "wedge": "楔",
    "clevis": "U形夹",
    "phillips": "菲利普斯",
    "cross": "十字",
    "recessed": "沉头",
    "fillister": "圆头",
    "head": "头",
    "metric": "公制",
    "helical": "螺旋",
    "threaded": "螺纹",
    "insert": "嵌件",
    "external": "外部",
    "whitworth": "惠氏",
    "bs": "BS",
    "kanban": "看板",
    "odor": "气味",
    "coulomb": "库仑",
    "active": "主动",
    "earth": "土",
    "compressibility": "可压缩性",
    "allowable": "允许",
    "piles": "桩",
    "required": "所需",
    "velocity": "速度",
    "sewers": "下水道",
    "ceiling": "天花板",
    "joist": "托梁",
    "span": "跨度",
    "live": "活",
    "dead": "静",
    "steady": "稳定",
    "state": "状态",
    "indoor": "室内",
    "slip": "滑移",
    "critical": "临界",
    "slot": "槽",
    "kinetic": "动能",
    "submerged": "浸没",
    "flagpole": "旗杆",
    "parshall": "帕歇尔",
    "flume": "水槽",
    "loan": "贷款",
    "canadian": "加拿大",
    "mortgage": "抵押",
    "lease": "租赁",
    "leasing": "租赁",
    "currency": "货币",
    "publications": "出版物",
    "unified": "统一",
    "series": "系列",
    "handbook": "手册",
    "enriched": "增强",
    "maximum": "最大",
    "material": "材料",
    "specific": "比重",
    "hot": "热",
    "balloon": "气球",
    "lifting": "提升",
    "wrought": "锻",
    "nodular": "球墨",
    "beryllium": "铍",
    "bernoulli": "伯努利",
    "euler": "欧拉",
    "lagrange": "拉格朗日",
    "nusselt": "努塞尔",
    "prandtl": "普朗特",
    "rayleigh": "瑞利",
    "peclet": "佩克莱",
    "grashof": "格拉肖夫",
    "mach": "马赫",
    "newton": "牛顿",
    "maxwell": "麦克斯韦",
    "fourier": "傅里叶",
    "laplace": "拉普拉斯",
    "navier": "纳维耶",
    "stokes": "斯托克斯",
    "wait": "等待",
    "holding": "保持",
    "container": "容器",
    "cargo": "货物",
    "freight": "货运",
    "passenger": "乘客",
    "forged": "锻",
    "nodular": "球墨",
    "malleable": "可锻",
    "centrifugal": "离心",
    "reciprocating": "往复",
    "rotary": "旋转",
    "oscillating": "摆动",
    "screw": "螺旋",
    "conveyor": "输送机",
    "elevator": "升降机",
    "propeller": "螺旋桨",
    "nozzle": "喷嘴",
    "diffuser": "扩压器",
    "impeller": "叶轮",
    "radial": "径向",
    "axial": "轴向",
    "tangential": "切向",
    "laminar": "层流",
    "turbulent": "湍流",
    "boundary": "边界",
    "layer": "层",
    "compressible": "可压缩",
    "incompressible": "不可压缩",
    "viscous": "黏性",
    "inviscid": "无黏",
    "potential": "势",
    "stream": "流",
    "function": "函数",
    "dimensionless": "无量纲",
    "equivalent": "等效",
    "effective": "有效",
    "nominal": "标称",
    "actual": "实际",
    "theoretical": "理论",
    "experimental": "实验",
    "numerical": "数值",
    "analytical": "解析",
    "graphical": "图解",
    "empirical": "经验",
    "dimension": "尺寸",
    "tolerance": "公差",
    "allowance": "余量",
    "clearance": "间隙",
    "interference": "过盈",
    "fit": "配合",
    "datum": "基准",
    "reference": "参考",
    "coordinate": "坐标",
    "dimensioning": "标注",
    "tolerancing": "公差",
    "geometric": "几何",
    "symbol": "符号",
    "abbreviation": "缩写",
    "notation": "符号",
    "convention": "约定",
    "representation": "表示",
    "view": "视图",
    "projection": "投影",
    "section": "剖面",
    "cutting": "剖切",
    "plane": "平面",
    "line": "线",
    "circle": "圆",
    "arc": "弧",
    "ellipse": "椭圆",
    "curve": "曲线",
    "point": "点",
    "center": "中心",
    "axis": "轴",
    "horizontal": "水平",
    "vertical": "垂直",
    "parallel": "平行",
    "perpendicular": "垂直",
    "concentric": "同心",
    "eccentric": "偏心",
    "symmetry": "对称",
    "asymmetry": "不对称",
    "alignment": "对准",
    "orientation": "方向",
    "position": "位置",
    "location": "位置",
    "profile": "轮廓",
    "contour": "等值线",
    "pattern": "模式",
    "layout": "布局",
    "configuration": "配置",
    "setup": "设置",
    "arrangement": "布置",
    "sequence": "顺序",
    "order": "次序",
    "step": "步骤",
    "stage": "阶段",
    "phase": "阶段",
    "iteration": "迭代",
    "loop": "循环",
    "recursion": "递归",
    "incremental": "增量",
    "finite": "有限",
    "element": "单元",
    "node": "节点",
    "mesh": "网格",
    "grid": "网格",
    "convergence": "收敛",
    "stability": "稳定",
    "accuracy": "精度",
    "error": "误差",
    "residual": "残差",
    "correction": "修正",
    "adjustment": "调整",
    "modification": "修改",
    "variation": "变化",
    "deviation": "偏差",
    "deflection": "挠度",
    "displacement": "位移",
    "deformation": "变形",
    "distortion": "畸变",
    "warpage": "翘曲",
    "expansion": "膨胀",
    "contraction": "收缩",

}


def has_chinese(s):
    return bool(re.search(r'[一-鿿]', s))


def main():
    print("=" * 60)
    print("Phase E4-fix-mixed: 修复中英混合翻译术语")
    print("=" * 60)

    v6 = json.loads((KB / "mech-terminology-v6.json").read_bytes())
    terms = v6.get("terms", [])

    # Find mixed terms
    mixed_terms = []
    for t in terms:
        zh = t.get("zh", "")
        if re.search(r'[a-zA-Z]', zh) and has_chinese(zh):
            mixed_terms.append(t)

    print(f"\n中英混合术语: {len(mixed_terms)}")

    fixed_count = 0
    failed_count = 0
    for t in mixed_terms:
        zh = t["zh"]
        en = t["en"]

        # Step 1: Reconstruct translation by replacing English words in zh
        new_zh = zh

        # Find all English words in the current zh
        en_words_in_zh = re.findall(r'[a-zA-Z]+', new_zh)
        for ew in sorted(en_words_in_zh, key=len, reverse=True):
            ew_lower = ew.lower()
            if ew_lower in WORD_FIXES:
                new_zh = new_zh.replace(ew, WORD_FIXES[ew_lower], 1)
            elif ew_lower in KNOWN_ACRONYMS:
                pass  # Keep acronyms
            else:
                # Try adding 's' (plural to singular)
                if ew_lower.endswith('s') and ew_lower[:-1] in WORD_FIXES:
                    new_zh = new_zh.replace(ew, WORD_FIXES[ew_lower[:-1]], 1)
                else:
                    failed_count += 1

        if new_zh != zh and not re.search(r'[a-zéèêëàâäùûüôöîïç]', new_zh):
            # Only accept if all lowercase English has been replaced
            remaining_en = [w for w in re.findall(r'[a-zA-Z]+', new_zh) if w[0].islower()]
            if not remaining_en:
                t["zh"] = new_zh
                t["translation_quality"] = "e4_fixed_mixed"
                t["source"] = t.get("source", "") + "+e4m"
                fixed_count += 1
                print(f"  ✓ {en:50s} '{zh:40s}' → '{new_zh}'")
            else:
                print(f"  ~ {en:50s} '{zh:40s}' → '{new_zh}' (remaining: {remaining_en})")
                # Fix remaining one by one
                for rw in remaining_en:
                    rw_lower = rw.lower()
                    if rw_lower in WORD_FIXES:
                        new_zh = new_zh.replace(rw, WORD_FIXES[rw_lower], 1)
                if new_zh != zh:
                    t["zh"] = new_zh
                    t["translation_quality"] = "e4_fixed_mixed"
                    t["source"] = t.get("source", "") + "+e4m"
                    fixed_count += 1
                    print(f"  ✓ {en:50s} '{zh:40s}' → '{new_zh}'")

    # Recalculate stats
    still_mixed = sum(1 for t in terms if re.search(r'[a-zA-Z]', t.get("zh", "")) and has_chinese(t.get("zh", "")))
    still_pure_en = sum(1 for t in terms if t.get("zh", "") and not has_chinese(t.get("zh", "")))
    good = sum(1 for t in terms if t.get("zh", "") and not re.search(r'[a-zA-Z]', t.get("zh", "")) and has_chinese(t.get("zh", "")))

    print(f"\n{'='*60}")
    print(f"修复: {fixed_count}, 剩余混合: {still_mixed}, 纯英文: {still_pure_en}, 合格: {good}")

    # Save v7
    v6["meta"]["version"] = "7"
    v6["meta"]["phase_e4m_fixed"] = fixed_count
    v6["meta"]["phase_e4m_remaining_mixed"] = still_mixed

    (KB / "mech-terminology-v7.json").write_text(
        json.dumps(v6, ensure_ascii=False, indent=2))
    print(f"\n✅ 已保存 v7")


if __name__ == "__main__":
    main()
